fixes missing directory issue when creating collectd.conf
ERROR: template[/opt/collectd/etc/collectd.conf] (collectd::default line 97) had an error: Chef::Exceptions::EnclosingDirectoryDoesNotExist: Parent directory /opt/collectd/etc does not exist